name: Commits
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  commits:
    permissions:
      pull-requests: read  # for tim-actions/get-pr-commits to get list of commits from the PR
    name: CLA check
    runs-on: ubuntu-22.04
    steps:
    - name: Check if CLA signed
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: simondeziel/has-signed-canonical-cla@main
