name: Commits
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  commits:
    name: CLA check
    runs-on: ubuntu-22.04
    steps:
    - name: Check if CLA signed
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: simondeziel/has-signed-canonical-cla@main
