name: Commits
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  commits:
    runs-on: ubuntu-22.04
    steps:
    - name: foo
      id: bar
      run: |
        set -x
        echo "1 ${{ steps.bar.name }}"
